[[mgr.prepend_keymap]]
on   = ["t", "l"]
run  = "plugin toggle-pane min-parent"
desc = "Show or hide the parent pane"

[[mgr.prepend_keymap]]
on   = ["t", "m"]
run  = "plugin toggle-pane min-current"
desc = "Show or hide the current pane"

[[mgr.prepend_keymap]]
on   = ["t", "r"]
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

# bookmarks
[[mgr.prepend_keymap]]
on = [ "u", "a" ]
run = "plugin yamb -- save"
desc = "Add bookmark"

[[mgr.prepend_keymap]]
on = [ "u", "g" ]
run = "plugin yamb -- jump_by_key"
desc = "Jump bookmark by key"

[[mgr.prepend_keymap]]
on = [ "u", "G" ]
run = "plugin yamb -- jump_by_fzf"
desc = "Jump bookmark by fzf"

[[mgr.prepend_keymap]]
on = [ "u", "d" ]
run = "plugin yamb -- delete_by_key"
desc = "Delete bookmark by key"

[[mgr.prepend_keymap]]
on = [ "u", "D" ]
run = "plugin yamb -- delete_by_fzf"
desc = "Delete bookmark by fzf"

[[mgr.prepend_keymap]]
on = [ "u", "A" , "D"]
run = "plugin yamb -- delete_all"
desc = "Delete all bookmarks"

[[mgr.prepend_keymap]]
on = [ "u", "r" ]
run = "plugin yamb -- rename_by_key"
desc = "Rename bookmark by key"

[[mgr.prepend_keymap]]
on = [ "u", "R" ]
run = "plugin yamb -- rename_by_fzf"
desc = "Rename bookmark by fzf"
