[[mgr.prepend_keymap]]
on   = ["t", "l"]
run  = "plugin toggle-pane min-parent"
desc = "Show or hide the parent pane"

[[mgr.prepend_keymap]]
on   = ["t", "m"]
run  = "plugin toggle-pane min-current"
desc = "Show or hide the current pane"

[[mgr.prepend_keymap]]
on   = ["t", "r"]
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"
